name: Build LaTeX Document

on:
  push:
    branches:
      - main  # Passe den Branch an
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. LaTeX-Datei mit pdflatex kompilieren (erster Lauf)
      - name: Run pdflatex (1st pass)
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler Ausarbeitung.tex

      # 3. Biber ausführen (für Literaturverzeichnis)
      - name: Run biber
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler biber Ausarbeitung

      # 4. LaTeX-Datei mit pdflatex erneut kompilieren (zweiter Lauf)
      - name: Run pdflatex (2nd pass)
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler Ausarbeitung.tex

      # 5. LaTeX-Datei mit pdflatex ein drittes Mal kompilieren (für Verzeichnisse)
      - name: Run pdflatex (3rd pass)
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler Ausarbeitung.tex

      # 6. PDF-Artefakt hochladen
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: Ausarbeitung/Ausarbeitung.pdf
