name: Build and Commit PDF

on:
  push:
    branches:
      - main  # Passe den Branch an
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Run pdflatex (1st pass)
      - name: Run pdflatex (1st pass)
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler Ausarbeitung.tex || echo "pdflatex completed with warnings"

      # 3. Run biber
      - name: Run biber
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler biber Ausarbeitung || echo "biber completed with warnings"

      # 4. Run pdflatex (2nd pass)
      - name: Run pdflatex (2nd pass)
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler Ausarbeitung.tex || echo "pdflatex completed with warnings"

      # 5. Run pdflatex (3rd pass)
      - name: Run pdflatex (3rd pass)
        run: |
          docker run --rm -v "${{ github.workspace }}/Ausarbeitung:/workspace" swfcloud/latexcompiler Ausarbeitung.tex || echo "pdflatex completed with warnings"

      # 6. Commit and push the PDF to the repository
      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cd Ausarbeitung
          git add Ausarbeitung.pdf
          git commit -m "Update compiled PDF"
          git push
        env:
          # GitHub Actions Token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
